



extern double theto[]; 
extern double dRcdp[], dRcdT[]; 
extern int GGWRC;
extern int CSWRC; 
extern int FYWRC; 

extern double nsteps; 
extern double delvel; 

double tempki[eC_MaxLev]; 

extern double den[eC_MaxLev]; 
extern double temp[eC_MaxLev];
extern double theta[eC_MaxLev]; 
extern double csxddd[];
extern double nlevel; 
extern double csd[eC_MaxLev]; 
extern double tempk[eC_MaxLev]; 
extern double vapres[eC_MaxLev]; 
extern double rhov[eC_MaxLev];
extern int MIXDIF; 
extern double tempr[];
extern int CONRD;
extern double Rcoef[];
extern double thpsin[eC_MaxLev]; 
extern double xm[], poros[];

extern double  psin[eC_MaxLev];

extern double thtemp[]; 
extern int ENHEV; 
extern int SORCE ;
extern int FILMFL; 
extern int SURFD; 
extern int GGHYD, GGHYB, VNHYD, BCHYD,VAHYD  ; 
extern int KELVN; 
extern int BRUSS ;
extern int MASSM ;
extern int NOVAK;
extern int MASSO ;
extern int DRYSV; 
extern double nl;   
extern int SORCE;
extern double difcoef,delz;
extern double bcta[],jstep,eta4[], Htrans, CE, CU; 
extern double bcQ[], bcra[];
extern double thpsini[]; 
extern int TMPWRC, THETAR; 
/*------------------------------------------------------------*/

bool LGL [eC_MaxLev];

double xlamv  [eC_MaxLev]; 

double temp1  [eC_MaxLev]; 
double psin1  [eC_MaxLev]; 
double rhov1  [eC_MaxLev]; 
double  TempR   [eC_MaxLev];
double  temR    [eC_MaxLev];
double  muv     [eC_MaxLev];
double  muvT    [eC_MaxLev];
double  zlamv   [eC_MaxLev];
double  zlavT   [eC_MaxLev]; 
double  denw    [eC_MaxLev];
double  denwi   [eC_MaxLev];
double  denwdT  [eC_MaxLev];
double  denwN   [eC_MaxLev];
double  muw     [eC_MaxLev]; 
double  muwT    [eC_MaxLev]; 
double  dmTm    [eC_MaxLev]; 
double  zlamw   [eC_MaxLev]; 
double  lawT    [eC_MaxLev]; 
double  xhiv    [eC_MaxLev];
double  dxhivdT [eC_MaxLev];
double  dxhivdr [eC_MaxLev];
double  zlamdd  [eC_MaxLev];
double  zlamda  [eC_MaxLev];
double  esat    [eC_MaxLev]; 
double  ss      [eC_MaxLev];
double  csat    [eC_MaxLev]; 
double  dcsatdT [eC_MaxLev]; 
double  stef    [eC_MaxLev];
double  stefpT  [eC_MaxLev];
double  stefpr  [eC_MaxLev];
double  diffa     [eC_MaxLev]; 
double  diffH     [eC_MaxLev]; 
double  diffs     [eC_MaxLev]; 
double  difsdT    [eC_MaxLev]; 
double  difsdr    [eC_MaxLev]; 
double  tcon      [eC_MaxLev];
double  tconR     [eC_MaxLev]; 
double  Kn        [eC_MaxLev]; 
double  KH        [eC_MaxLev]; 
double  dKHdT     [eC_MaxLev]; 
double  dKHdt     [eC_MaxLev];  
double  dKHdp     [eC_MaxLev]; 
double  sourcev   [eC_MaxLev]; 
double  dSvdT     [eC_MaxLev]; 
double  dSvdp     [eC_MaxLev]; 
double  dSvdr     [eC_MaxLev]; 
double  Srhov     [eC_MaxLev]; 
double  tcona     [eC_MaxLev];
double  xa        [eC_MaxLev];
double  fw        [eC_MaxLev];
double  hv        [eC_MaxLev];
double  dhvdT     [eC_MaxLev];
double  ka        [eC_MaxLev];
double  dstensdT  [eC_MaxLev];
double  enh      [eC_MaxLev]; 
double  vdiff    [eC_MaxLev]; 
double  lv       [eC_MaxLev]; 
double  DiffT    [eC_MaxLev]; 
double  denwnT   [eC_MaxLev]; 
double  cs       [eC_MaxLev]; 
double  csi      [eC_MaxLev]; 
double  sdialc   [eC_MaxLev];
double  ddiaT    [eC_MaxLev];
double  stensn   [eC_MaxLev];
double  KnF      [eC_MaxLev];
double  KHF      [eC_MaxLev];
double  dKnFdT   [eC_MaxLev];
double  dKnFdp   [eC_MaxLev];
double  dKHFdT   [eC_MaxLev];
double  dKHFdp   [eC_MaxLev];
double  Sw       [eC_MaxLev];
double  mug      [eC_MaxLev]; 
double  rhcpv    [eC_MaxLev]; 
double  rhcpa    [eC_MaxLev];
double  Dummy1   [eC_MaxLev];
double  Dummy2   [eC_MaxLev]; 
double  rh       [eC_MaxLev]; 
double  rhove    [eC_MaxLev]; 
double  drevdp   [eC_MaxLev]; 
double  drevdT   [eC_MaxLev];  
double  Kd       [eC_MaxLev]; 
double  Km       [eC_MaxLev]; 
double  Awa      [eC_MaxLev]; 
double  dAwadt   [eC_MaxLev]; 
double  dAwadp   [eC_MaxLev]; 
double  Concf    [eC_MaxLev]; 
double  dCondT   [eC_MaxLev]; 
double  dCondp   [eC_MaxLev]; 
double  u        [eC_MaxLev]; 
double  delu     [eC_MaxLev]; 
double  advdif   [eC_MaxLev]; 
double  adtcon   [eC_MaxLev]; 
double  diseq    [eC_MaxLev ];
double csx     [eC_MaxLev];  
double mud     [eC_MaxLev];  
double uu1     [eC_MaxLev];
double aaQ     [eC_MaxLev]; 
double Lambdau [eC_MaxLev]; 
double  ugrad  [eC_MaxLev];    
double  xxQ    [eC_MaxLev]; 
double  yyQ    [eC_MaxLev]; 
double  zzQ    [eC_MaxLev];    
double theta1 [eC_MaxLev]; 

/* These are used for the Hamonic Mean and need to be */
/*  one size bigger */ 
double hcon   [eC_MaxLev+1];
double hvdif  [eC_MaxLev+1];
double hKn    [eC_MaxLev+1];
double hKm    [eC_MaxLev+1];
double hDifT  [eC_MaxLev+1];

int LGLth  [eC_MaxLev];

double denlv  [eC_MaxLev+1];
double Gama   [eC_MaxLev+1];
double ktcon  [eC_MaxLev+1];
double lacon  [eC_MaxLev+1];
double denthi [eC_MaxLev+1];
double dlvl   [eC_MaxLev+1];
double xai    [eC_MaxLev+1]; 
double xaida  [eC_MaxLev+1];
double RV     [eC_MaxLev+1]; 
double Ai11   [eC_MaxLev+1]; 
double Ai12   [eC_MaxLev+1]; 
double Ai13   [eC_MaxLev+1]; 
double Ai21   [eC_MaxLev+1]; 
double Ai22   [eC_MaxLev+1]; 
double Ai23   [eC_MaxLev+1]; 
double Ai31   [eC_MaxLev+1]; 
double Ai32   [eC_MaxLev+1]; 
double Ai33   [eC_MaxLev+1]; 
double Api11  [eC_MaxLev+1]; 
double Api12  [eC_MaxLev+1]; 
double Api13  [eC_MaxLev+1]; 
double Api21  [eC_MaxLev+1]; 
double Api22  [eC_MaxLev+1]; 
double Api23  [eC_MaxLev+1]; 
double Api31  [eC_MaxLev+1]; 
double Api32  [eC_MaxLev+1]; 
double Api33  [eC_MaxLev+1]; 
double Bi11   [eC_MaxLev+1]; 
double Bi12   [eC_MaxLev+1]; 
double Bi13  [eC_MaxLev+1];  
double Bi21  [eC_MaxLev+1];  
double Bi22   [eC_MaxLev+1]; 
double Bi23   [eC_MaxLev+1]; 
double Bi31   [eC_MaxLev+1]; 
double Bi32   [eC_MaxLev+1]; 
double Bi33   [eC_MaxLev+1]; 
double Bpi11  [eC_MaxLev+1]; 
double Bpi12  [eC_MaxLev+1]; 
double Bpi13  [eC_MaxLev+1]; 
double Bpi21  [eC_MaxLev+1]; 
double Bpi22  [eC_MaxLev+1]; 
double Bpi23  [eC_MaxLev+1]; 
double Bpi31  [eC_MaxLev+1]; 
double Bpi32  [eC_MaxLev+1]; 
double Bpi33  [eC_MaxLev+1]; 
double Ci11   [eC_MaxLev+1]; 
double Ci12   [eC_MaxLev+1]; 
double Ci13   [eC_MaxLev+1]; 
double Ci21   [eC_MaxLev+1]; 
double Ci22   [eC_MaxLev+1]; 
double Ci23   [eC_MaxLev+1]; 
double Ci31   [eC_MaxLev+1]; 
double Ci32   [eC_MaxLev+1]; 
double Ci33   [eC_MaxLev+1]; 
double Cpi11  [eC_MaxLev+1]; 
double Cpi12  [eC_MaxLev+1]; 
double Cpi13  [eC_MaxLev+1]; 
double Cpi21  [eC_MaxLev+1]; 
double Cpi22  [eC_MaxLev+1]; 
double Cpi23  [eC_MaxLev+1]; 
double Cpi31  [eC_MaxLev+1]; 
double Cpi32  [eC_MaxLev+1]; 
double Cpi33  [eC_MaxLev+1]; 
double Ri1    [eC_MaxLev+1]; 
double Ri2    [eC_MaxLev+1]; 
double Ri3    [eC_MaxLev+1]; 

int _Alloc_Arrays ();
extern double nsteps; 