# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jessica/Documents/fofem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jessica/Documents/fofem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jessica/Documents/fofem/CMakeFiles /Users/jessica/Documents/fofem//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jessica/Documents/fofem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fofem

# Build rule for target.
fofem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fofem
.PHONY : fofem

# fast build rule for target.
fofem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/build
.PHONY : fofem/fast

#=============================================================================
# Target rules for targets named fofem_c

# Build rule for target.
fofem_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fofem_c
.PHONY : fofem_c

# fast build rule for target.
fofem_c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/build
.PHONY : fofem_c/fast

FOF_UNIX/ansi_mai.o: FOF_UNIX/ansi_mai.cpp.o
.PHONY : FOF_UNIX/ansi_mai.o

# target to build an object file
FOF_UNIX/ansi_mai.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/ansi_mai.cpp.o
.PHONY : FOF_UNIX/ansi_mai.cpp.o

FOF_UNIX/ansi_mai.i: FOF_UNIX/ansi_mai.cpp.i
.PHONY : FOF_UNIX/ansi_mai.i

# target to preprocess a source file
FOF_UNIX/ansi_mai.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/ansi_mai.cpp.i
.PHONY : FOF_UNIX/ansi_mai.cpp.i

FOF_UNIX/ansi_mai.s: FOF_UNIX/ansi_mai.cpp.s
.PHONY : FOF_UNIX/ansi_mai.s

# target to generate assembly for a file
FOF_UNIX/ansi_mai.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/ansi_mai.cpp.s
.PHONY : FOF_UNIX/ansi_mai.cpp.s

FOF_UNIX/bur_bov.o: FOF_UNIX/bur_bov.cpp.o
.PHONY : FOF_UNIX/bur_bov.o

# target to build an object file
FOF_UNIX/bur_bov.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/bur_bov.cpp.o
.PHONY : FOF_UNIX/bur_bov.cpp.o

FOF_UNIX/bur_bov.i: FOF_UNIX/bur_bov.cpp.i
.PHONY : FOF_UNIX/bur_bov.i

# target to preprocess a source file
FOF_UNIX/bur_bov.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/bur_bov.cpp.i
.PHONY : FOF_UNIX/bur_bov.cpp.i

FOF_UNIX/bur_bov.s: FOF_UNIX/bur_bov.cpp.s
.PHONY : FOF_UNIX/bur_bov.s

# target to generate assembly for a file
FOF_UNIX/bur_bov.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/bur_bov.cpp.s
.PHONY : FOF_UNIX/bur_bov.cpp.s

FOF_UNIX/bur_brn.o: FOF_UNIX/bur_brn.cpp.o
.PHONY : FOF_UNIX/bur_brn.o

# target to build an object file
FOF_UNIX/bur_brn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/bur_brn.cpp.o
.PHONY : FOF_UNIX/bur_brn.cpp.o

FOF_UNIX/bur_brn.i: FOF_UNIX/bur_brn.cpp.i
.PHONY : FOF_UNIX/bur_brn.i

# target to preprocess a source file
FOF_UNIX/bur_brn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/bur_brn.cpp.i
.PHONY : FOF_UNIX/bur_brn.cpp.i

FOF_UNIX/bur_brn.s: FOF_UNIX/bur_brn.cpp.s
.PHONY : FOF_UNIX/bur_brn.s

# target to generate assembly for a file
FOF_UNIX/bur_brn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/bur_brn.cpp.s
.PHONY : FOF_UNIX/bur_brn.cpp.s

FOF_UNIX/cdf_util.o: FOF_UNIX/cdf_util.cpp.o
.PHONY : FOF_UNIX/cdf_util.o

# target to build an object file
FOF_UNIX/cdf_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/cdf_util.cpp.o
.PHONY : FOF_UNIX/cdf_util.cpp.o

FOF_UNIX/cdf_util.i: FOF_UNIX/cdf_util.cpp.i
.PHONY : FOF_UNIX/cdf_util.i

# target to preprocess a source file
FOF_UNIX/cdf_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/cdf_util.cpp.i
.PHONY : FOF_UNIX/cdf_util.cpp.i

FOF_UNIX/cdf_util.s: FOF_UNIX/cdf_util.cpp.s
.PHONY : FOF_UNIX/cdf_util.s

# target to generate assembly for a file
FOF_UNIX/cdf_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/cdf_util.cpp.s
.PHONY : FOF_UNIX/cdf_util.cpp.s

FOF_UNIX/fof_bcm.o: FOF_UNIX/fof_bcm.cpp.o
.PHONY : FOF_UNIX/fof_bcm.o

# target to build an object file
FOF_UNIX/fof_bcm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_bcm.cpp.o
.PHONY : FOF_UNIX/fof_bcm.cpp.o

FOF_UNIX/fof_bcm.i: FOF_UNIX/fof_bcm.cpp.i
.PHONY : FOF_UNIX/fof_bcm.i

# target to preprocess a source file
FOF_UNIX/fof_bcm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_bcm.cpp.i
.PHONY : FOF_UNIX/fof_bcm.cpp.i

FOF_UNIX/fof_bcm.s: FOF_UNIX/fof_bcm.cpp.s
.PHONY : FOF_UNIX/fof_bcm.s

# target to generate assembly for a file
FOF_UNIX/fof_bcm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_bcm.cpp.s
.PHONY : FOF_UNIX/fof_bcm.cpp.s

FOF_UNIX/fof_ci.o: FOF_UNIX/fof_ci.cpp.o
.PHONY : FOF_UNIX/fof_ci.o

# target to build an object file
FOF_UNIX/fof_ci.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_ci.cpp.o
.PHONY : FOF_UNIX/fof_ci.cpp.o

FOF_UNIX/fof_ci.i: FOF_UNIX/fof_ci.cpp.i
.PHONY : FOF_UNIX/fof_ci.i

# target to preprocess a source file
FOF_UNIX/fof_ci.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_ci.cpp.i
.PHONY : FOF_UNIX/fof_ci.cpp.i

FOF_UNIX/fof_ci.s: FOF_UNIX/fof_ci.cpp.s
.PHONY : FOF_UNIX/fof_ci.s

# target to generate assembly for a file
FOF_UNIX/fof_ci.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_ci.cpp.s
.PHONY : FOF_UNIX/fof_ci.cpp.s

FOF_UNIX/fof_cm.o: FOF_UNIX/fof_cm.cpp.o
.PHONY : FOF_UNIX/fof_cm.o

# target to build an object file
FOF_UNIX/fof_cm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_cm.cpp.o
.PHONY : FOF_UNIX/fof_cm.cpp.o

FOF_UNIX/fof_cm.i: FOF_UNIX/fof_cm.cpp.i
.PHONY : FOF_UNIX/fof_cm.i

# target to preprocess a source file
FOF_UNIX/fof_cm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_cm.cpp.i
.PHONY : FOF_UNIX/fof_cm.cpp.i

FOF_UNIX/fof_cm.s: FOF_UNIX/fof_cm.cpp.s
.PHONY : FOF_UNIX/fof_cm.s

# target to generate assembly for a file
FOF_UNIX/fof_cm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_cm.cpp.s
.PHONY : FOF_UNIX/fof_cm.cpp.s

FOF_UNIX/fof_co.o: FOF_UNIX/fof_co.cpp.o
.PHONY : FOF_UNIX/fof_co.o

# target to build an object file
FOF_UNIX/fof_co.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_co.cpp.o
.PHONY : FOF_UNIX/fof_co.cpp.o

FOF_UNIX/fof_co.i: FOF_UNIX/fof_co.cpp.i
.PHONY : FOF_UNIX/fof_co.i

# target to preprocess a source file
FOF_UNIX/fof_co.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_co.cpp.i
.PHONY : FOF_UNIX/fof_co.cpp.i

FOF_UNIX/fof_co.s: FOF_UNIX/fof_co.cpp.s
.PHONY : FOF_UNIX/fof_co.s

# target to generate assembly for a file
FOF_UNIX/fof_co.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_co.cpp.s
.PHONY : FOF_UNIX/fof_co.cpp.s

FOF_UNIX/fof_disp.o: FOF_UNIX/fof_disp.cpp.o
.PHONY : FOF_UNIX/fof_disp.o

# target to build an object file
FOF_UNIX/fof_disp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_disp.cpp.o
.PHONY : FOF_UNIX/fof_disp.cpp.o

FOF_UNIX/fof_disp.i: FOF_UNIX/fof_disp.cpp.i
.PHONY : FOF_UNIX/fof_disp.i

# target to preprocess a source file
FOF_UNIX/fof_disp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_disp.cpp.i
.PHONY : FOF_UNIX/fof_disp.cpp.i

FOF_UNIX/fof_disp.s: FOF_UNIX/fof_disp.cpp.s
.PHONY : FOF_UNIX/fof_disp.s

# target to generate assembly for a file
FOF_UNIX/fof_disp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_disp.cpp.s
.PHONY : FOF_UNIX/fof_disp.cpp.s

FOF_UNIX/fof_duf.o: FOF_UNIX/fof_duf.cpp.o
.PHONY : FOF_UNIX/fof_duf.o

# target to build an object file
FOF_UNIX/fof_duf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_duf.cpp.o
.PHONY : FOF_UNIX/fof_duf.cpp.o

FOF_UNIX/fof_duf.i: FOF_UNIX/fof_duf.cpp.i
.PHONY : FOF_UNIX/fof_duf.i

# target to preprocess a source file
FOF_UNIX/fof_duf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_duf.cpp.i
.PHONY : FOF_UNIX/fof_duf.cpp.i

FOF_UNIX/fof_duf.s: FOF_UNIX/fof_duf.cpp.s
.PHONY : FOF_UNIX/fof_duf.s

# target to generate assembly for a file
FOF_UNIX/fof_duf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_duf.cpp.s
.PHONY : FOF_UNIX/fof_duf.cpp.s

FOF_UNIX/fof_hsf.o: FOF_UNIX/fof_hsf.cpp.o
.PHONY : FOF_UNIX/fof_hsf.o

# target to build an object file
FOF_UNIX/fof_hsf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_hsf.cpp.o
.PHONY : FOF_UNIX/fof_hsf.cpp.o

FOF_UNIX/fof_hsf.i: FOF_UNIX/fof_hsf.cpp.i
.PHONY : FOF_UNIX/fof_hsf.i

# target to preprocess a source file
FOF_UNIX/fof_hsf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_hsf.cpp.i
.PHONY : FOF_UNIX/fof_hsf.cpp.i

FOF_UNIX/fof_hsf.s: FOF_UNIX/fof_hsf.cpp.s
.PHONY : FOF_UNIX/fof_hsf.s

# target to generate assembly for a file
FOF_UNIX/fof_hsf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_hsf.cpp.s
.PHONY : FOF_UNIX/fof_hsf.cpp.s

FOF_UNIX/fof_lem.o: FOF_UNIX/fof_lem.cpp.o
.PHONY : FOF_UNIX/fof_lem.o

# target to build an object file
FOF_UNIX/fof_lem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_lem.cpp.o
.PHONY : FOF_UNIX/fof_lem.cpp.o

FOF_UNIX/fof_lem.i: FOF_UNIX/fof_lem.cpp.i
.PHONY : FOF_UNIX/fof_lem.i

# target to preprocess a source file
FOF_UNIX/fof_lem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_lem.cpp.i
.PHONY : FOF_UNIX/fof_lem.cpp.i

FOF_UNIX/fof_lem.s: FOF_UNIX/fof_lem.cpp.s
.PHONY : FOF_UNIX/fof_lem.s

# target to generate assembly for a file
FOF_UNIX/fof_lem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_lem.cpp.s
.PHONY : FOF_UNIX/fof_lem.cpp.s

FOF_UNIX/fof_mrt.o: FOF_UNIX/fof_mrt.cpp.o
.PHONY : FOF_UNIX/fof_mrt.o

# target to build an object file
FOF_UNIX/fof_mrt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_mrt.cpp.o
.PHONY : FOF_UNIX/fof_mrt.cpp.o

FOF_UNIX/fof_mrt.i: FOF_UNIX/fof_mrt.cpp.i
.PHONY : FOF_UNIX/fof_mrt.i

# target to preprocess a source file
FOF_UNIX/fof_mrt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_mrt.cpp.i
.PHONY : FOF_UNIX/fof_mrt.cpp.i

FOF_UNIX/fof_mrt.s: FOF_UNIX/fof_mrt.cpp.s
.PHONY : FOF_UNIX/fof_mrt.s

# target to generate assembly for a file
FOF_UNIX/fof_mrt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_mrt.cpp.s
.PHONY : FOF_UNIX/fof_mrt.cpp.s

FOF_UNIX/fof_nes.o: FOF_UNIX/fof_nes.cpp.o
.PHONY : FOF_UNIX/fof_nes.o

# target to build an object file
FOF_UNIX/fof_nes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_nes.cpp.o
.PHONY : FOF_UNIX/fof_nes.cpp.o

FOF_UNIX/fof_nes.i: FOF_UNIX/fof_nes.cpp.i
.PHONY : FOF_UNIX/fof_nes.i

# target to preprocess a source file
FOF_UNIX/fof_nes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_nes.cpp.i
.PHONY : FOF_UNIX/fof_nes.cpp.i

FOF_UNIX/fof_nes.s: FOF_UNIX/fof_nes.cpp.s
.PHONY : FOF_UNIX/fof_nes.s

# target to generate assembly for a file
FOF_UNIX/fof_nes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_nes.cpp.s
.PHONY : FOF_UNIX/fof_nes.cpp.s

FOF_UNIX/fof_sd.o: FOF_UNIX/fof_sd.cpp.o
.PHONY : FOF_UNIX/fof_sd.o

# target to build an object file
FOF_UNIX/fof_sd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sd.cpp.o
.PHONY : FOF_UNIX/fof_sd.cpp.o

FOF_UNIX/fof_sd.i: FOF_UNIX/fof_sd.cpp.i
.PHONY : FOF_UNIX/fof_sd.i

# target to preprocess a source file
FOF_UNIX/fof_sd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sd.cpp.i
.PHONY : FOF_UNIX/fof_sd.cpp.i

FOF_UNIX/fof_sd.s: FOF_UNIX/fof_sd.cpp.s
.PHONY : FOF_UNIX/fof_sd.s

# target to generate assembly for a file
FOF_UNIX/fof_sd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sd.cpp.s
.PHONY : FOF_UNIX/fof_sd.cpp.s

FOF_UNIX/fof_se.o: FOF_UNIX/fof_se.cpp.o
.PHONY : FOF_UNIX/fof_se.o

# target to build an object file
FOF_UNIX/fof_se.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_se.cpp.o
.PHONY : FOF_UNIX/fof_se.cpp.o

FOF_UNIX/fof_se.i: FOF_UNIX/fof_se.cpp.i
.PHONY : FOF_UNIX/fof_se.i

# target to preprocess a source file
FOF_UNIX/fof_se.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_se.cpp.i
.PHONY : FOF_UNIX/fof_se.cpp.i

FOF_UNIX/fof_se.s: FOF_UNIX/fof_se.cpp.s
.PHONY : FOF_UNIX/fof_se.s

# target to generate assembly for a file
FOF_UNIX/fof_se.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_se.cpp.s
.PHONY : FOF_UNIX/fof_se.cpp.s

FOF_UNIX/fof_sgv.o: FOF_UNIX/fof_sgv.cpp.o
.PHONY : FOF_UNIX/fof_sgv.o

# target to build an object file
FOF_UNIX/fof_sgv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sgv.cpp.o
.PHONY : FOF_UNIX/fof_sgv.cpp.o

FOF_UNIX/fof_sgv.i: FOF_UNIX/fof_sgv.cpp.i
.PHONY : FOF_UNIX/fof_sgv.i

# target to preprocess a source file
FOF_UNIX/fof_sgv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sgv.cpp.i
.PHONY : FOF_UNIX/fof_sgv.cpp.i

FOF_UNIX/fof_sgv.s: FOF_UNIX/fof_sgv.cpp.s
.PHONY : FOF_UNIX/fof_sgv.s

# target to generate assembly for a file
FOF_UNIX/fof_sgv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sgv.cpp.s
.PHONY : FOF_UNIX/fof_sgv.cpp.s

FOF_UNIX/fof_sh.o: FOF_UNIX/fof_sh.cpp.o
.PHONY : FOF_UNIX/fof_sh.o

# target to build an object file
FOF_UNIX/fof_sh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sh.cpp.o
.PHONY : FOF_UNIX/fof_sh.cpp.o

FOF_UNIX/fof_sh.i: FOF_UNIX/fof_sh.cpp.i
.PHONY : FOF_UNIX/fof_sh.i

# target to preprocess a source file
FOF_UNIX/fof_sh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sh.cpp.i
.PHONY : FOF_UNIX/fof_sh.cpp.i

FOF_UNIX/fof_sh.s: FOF_UNIX/fof_sh.cpp.s
.PHONY : FOF_UNIX/fof_sh.s

# target to generate assembly for a file
FOF_UNIX/fof_sh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sh.cpp.s
.PHONY : FOF_UNIX/fof_sh.cpp.s

FOF_UNIX/fof_sha.o: FOF_UNIX/fof_sha.cpp.o
.PHONY : FOF_UNIX/fof_sha.o

# target to build an object file
FOF_UNIX/fof_sha.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sha.cpp.o
.PHONY : FOF_UNIX/fof_sha.cpp.o

FOF_UNIX/fof_sha.i: FOF_UNIX/fof_sha.cpp.i
.PHONY : FOF_UNIX/fof_sha.i

# target to preprocess a source file
FOF_UNIX/fof_sha.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sha.cpp.i
.PHONY : FOF_UNIX/fof_sha.cpp.i

FOF_UNIX/fof_sha.s: FOF_UNIX/fof_sha.cpp.s
.PHONY : FOF_UNIX/fof_sha.s

# target to generate assembly for a file
FOF_UNIX/fof_sha.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_sha.cpp.s
.PHONY : FOF_UNIX/fof_sha.cpp.s

FOF_UNIX/fof_soi.o: FOF_UNIX/fof_soi.cpp.o
.PHONY : FOF_UNIX/fof_soi.o

# target to build an object file
FOF_UNIX/fof_soi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_soi.cpp.o
.PHONY : FOF_UNIX/fof_soi.cpp.o

FOF_UNIX/fof_soi.i: FOF_UNIX/fof_soi.cpp.i
.PHONY : FOF_UNIX/fof_soi.i

# target to preprocess a source file
FOF_UNIX/fof_soi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_soi.cpp.i
.PHONY : FOF_UNIX/fof_soi.cpp.i

FOF_UNIX/fof_soi.s: FOF_UNIX/fof_soi.cpp.s
.PHONY : FOF_UNIX/fof_soi.s

# target to generate assembly for a file
FOF_UNIX/fof_soi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_soi.cpp.s
.PHONY : FOF_UNIX/fof_soi.cpp.s

FOF_UNIX/fof_unix.o: FOF_UNIX/fof_unix.cpp.o
.PHONY : FOF_UNIX/fof_unix.o

# target to build an object file
FOF_UNIX/fof_unix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_unix.cpp.o
.PHONY : FOF_UNIX/fof_unix.cpp.o

FOF_UNIX/fof_unix.i: FOF_UNIX/fof_unix.cpp.i
.PHONY : FOF_UNIX/fof_unix.i

# target to preprocess a source file
FOF_UNIX/fof_unix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_unix.cpp.i
.PHONY : FOF_UNIX/fof_unix.cpp.i

FOF_UNIX/fof_unix.s: FOF_UNIX/fof_unix.cpp.s
.PHONY : FOF_UNIX/fof_unix.s

# target to generate assembly for a file
FOF_UNIX/fof_unix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_unix.cpp.s
.PHONY : FOF_UNIX/fof_unix.cpp.s

FOF_UNIX/fof_util.o: FOF_UNIX/fof_util.cpp.o
.PHONY : FOF_UNIX/fof_util.o

# target to build an object file
FOF_UNIX/fof_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_util.cpp.o
.PHONY : FOF_UNIX/fof_util.cpp.o

FOF_UNIX/fof_util.i: FOF_UNIX/fof_util.cpp.i
.PHONY : FOF_UNIX/fof_util.i

# target to preprocess a source file
FOF_UNIX/fof_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_util.cpp.i
.PHONY : FOF_UNIX/fof_util.cpp.i

FOF_UNIX/fof_util.s: FOF_UNIX/fof_util.cpp.s
.PHONY : FOF_UNIX/fof_util.s

# target to generate assembly for a file
FOF_UNIX/fof_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem.dir/build.make CMakeFiles/fofem.dir/FOF_UNIX/fof_util.cpp.s
.PHONY : FOF_UNIX/fof_util.cpp.s

FOF_UNIX_LIB/ansi_mai.o: FOF_UNIX_LIB/ansi_mai.cpp.o
.PHONY : FOF_UNIX_LIB/ansi_mai.o

# target to build an object file
FOF_UNIX_LIB/ansi_mai.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/ansi_mai.cpp.o
.PHONY : FOF_UNIX_LIB/ansi_mai.cpp.o

FOF_UNIX_LIB/ansi_mai.i: FOF_UNIX_LIB/ansi_mai.cpp.i
.PHONY : FOF_UNIX_LIB/ansi_mai.i

# target to preprocess a source file
FOF_UNIX_LIB/ansi_mai.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/ansi_mai.cpp.i
.PHONY : FOF_UNIX_LIB/ansi_mai.cpp.i

FOF_UNIX_LIB/ansi_mai.s: FOF_UNIX_LIB/ansi_mai.cpp.s
.PHONY : FOF_UNIX_LIB/ansi_mai.s

# target to generate assembly for a file
FOF_UNIX_LIB/ansi_mai.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/ansi_mai.cpp.s
.PHONY : FOF_UNIX_LIB/ansi_mai.cpp.s

FOF_UNIX_LIB/bur_bov.o: FOF_UNIX_LIB/bur_bov.cpp.o
.PHONY : FOF_UNIX_LIB/bur_bov.o

# target to build an object file
FOF_UNIX_LIB/bur_bov.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/bur_bov.cpp.o
.PHONY : FOF_UNIX_LIB/bur_bov.cpp.o

FOF_UNIX_LIB/bur_bov.i: FOF_UNIX_LIB/bur_bov.cpp.i
.PHONY : FOF_UNIX_LIB/bur_bov.i

# target to preprocess a source file
FOF_UNIX_LIB/bur_bov.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/bur_bov.cpp.i
.PHONY : FOF_UNIX_LIB/bur_bov.cpp.i

FOF_UNIX_LIB/bur_bov.s: FOF_UNIX_LIB/bur_bov.cpp.s
.PHONY : FOF_UNIX_LIB/bur_bov.s

# target to generate assembly for a file
FOF_UNIX_LIB/bur_bov.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/bur_bov.cpp.s
.PHONY : FOF_UNIX_LIB/bur_bov.cpp.s

FOF_UNIX_LIB/bur_brn.o: FOF_UNIX_LIB/bur_brn.cpp.o
.PHONY : FOF_UNIX_LIB/bur_brn.o

# target to build an object file
FOF_UNIX_LIB/bur_brn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/bur_brn.cpp.o
.PHONY : FOF_UNIX_LIB/bur_brn.cpp.o

FOF_UNIX_LIB/bur_brn.i: FOF_UNIX_LIB/bur_brn.cpp.i
.PHONY : FOF_UNIX_LIB/bur_brn.i

# target to preprocess a source file
FOF_UNIX_LIB/bur_brn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/bur_brn.cpp.i
.PHONY : FOF_UNIX_LIB/bur_brn.cpp.i

FOF_UNIX_LIB/bur_brn.s: FOF_UNIX_LIB/bur_brn.cpp.s
.PHONY : FOF_UNIX_LIB/bur_brn.s

# target to generate assembly for a file
FOF_UNIX_LIB/bur_brn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/bur_brn.cpp.s
.PHONY : FOF_UNIX_LIB/bur_brn.cpp.s

FOF_UNIX_LIB/cdf_util.o: FOF_UNIX_LIB/cdf_util.cpp.o
.PHONY : FOF_UNIX_LIB/cdf_util.o

# target to build an object file
FOF_UNIX_LIB/cdf_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/cdf_util.cpp.o
.PHONY : FOF_UNIX_LIB/cdf_util.cpp.o

FOF_UNIX_LIB/cdf_util.i: FOF_UNIX_LIB/cdf_util.cpp.i
.PHONY : FOF_UNIX_LIB/cdf_util.i

# target to preprocess a source file
FOF_UNIX_LIB/cdf_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/cdf_util.cpp.i
.PHONY : FOF_UNIX_LIB/cdf_util.cpp.i

FOF_UNIX_LIB/cdf_util.s: FOF_UNIX_LIB/cdf_util.cpp.s
.PHONY : FOF_UNIX_LIB/cdf_util.s

# target to generate assembly for a file
FOF_UNIX_LIB/cdf_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/cdf_util.cpp.s
.PHONY : FOF_UNIX_LIB/cdf_util.cpp.s

FOF_UNIX_LIB/fof_bcm.o: FOF_UNIX_LIB/fof_bcm.cpp.o
.PHONY : FOF_UNIX_LIB/fof_bcm.o

# target to build an object file
FOF_UNIX_LIB/fof_bcm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_bcm.cpp.o
.PHONY : FOF_UNIX_LIB/fof_bcm.cpp.o

FOF_UNIX_LIB/fof_bcm.i: FOF_UNIX_LIB/fof_bcm.cpp.i
.PHONY : FOF_UNIX_LIB/fof_bcm.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_bcm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_bcm.cpp.i
.PHONY : FOF_UNIX_LIB/fof_bcm.cpp.i

FOF_UNIX_LIB/fof_bcm.s: FOF_UNIX_LIB/fof_bcm.cpp.s
.PHONY : FOF_UNIX_LIB/fof_bcm.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_bcm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_bcm.cpp.s
.PHONY : FOF_UNIX_LIB/fof_bcm.cpp.s

FOF_UNIX_LIB/fof_ci.o: FOF_UNIX_LIB/fof_ci.cpp.o
.PHONY : FOF_UNIX_LIB/fof_ci.o

# target to build an object file
FOF_UNIX_LIB/fof_ci.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_ci.cpp.o
.PHONY : FOF_UNIX_LIB/fof_ci.cpp.o

FOF_UNIX_LIB/fof_ci.i: FOF_UNIX_LIB/fof_ci.cpp.i
.PHONY : FOF_UNIX_LIB/fof_ci.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_ci.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_ci.cpp.i
.PHONY : FOF_UNIX_LIB/fof_ci.cpp.i

FOF_UNIX_LIB/fof_ci.s: FOF_UNIX_LIB/fof_ci.cpp.s
.PHONY : FOF_UNIX_LIB/fof_ci.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_ci.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_ci.cpp.s
.PHONY : FOF_UNIX_LIB/fof_ci.cpp.s

FOF_UNIX_LIB/fof_cm.o: FOF_UNIX_LIB/fof_cm.cpp.o
.PHONY : FOF_UNIX_LIB/fof_cm.o

# target to build an object file
FOF_UNIX_LIB/fof_cm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_cm.cpp.o
.PHONY : FOF_UNIX_LIB/fof_cm.cpp.o

FOF_UNIX_LIB/fof_cm.i: FOF_UNIX_LIB/fof_cm.cpp.i
.PHONY : FOF_UNIX_LIB/fof_cm.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_cm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_cm.cpp.i
.PHONY : FOF_UNIX_LIB/fof_cm.cpp.i

FOF_UNIX_LIB/fof_cm.s: FOF_UNIX_LIB/fof_cm.cpp.s
.PHONY : FOF_UNIX_LIB/fof_cm.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_cm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_cm.cpp.s
.PHONY : FOF_UNIX_LIB/fof_cm.cpp.s

FOF_UNIX_LIB/fof_co.o: FOF_UNIX_LIB/fof_co.cpp.o
.PHONY : FOF_UNIX_LIB/fof_co.o

# target to build an object file
FOF_UNIX_LIB/fof_co.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_co.cpp.o
.PHONY : FOF_UNIX_LIB/fof_co.cpp.o

FOF_UNIX_LIB/fof_co.i: FOF_UNIX_LIB/fof_co.cpp.i
.PHONY : FOF_UNIX_LIB/fof_co.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_co.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_co.cpp.i
.PHONY : FOF_UNIX_LIB/fof_co.cpp.i

FOF_UNIX_LIB/fof_co.s: FOF_UNIX_LIB/fof_co.cpp.s
.PHONY : FOF_UNIX_LIB/fof_co.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_co.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_co.cpp.s
.PHONY : FOF_UNIX_LIB/fof_co.cpp.s

FOF_UNIX_LIB/fof_disp.o: FOF_UNIX_LIB/fof_disp.cpp.o
.PHONY : FOF_UNIX_LIB/fof_disp.o

# target to build an object file
FOF_UNIX_LIB/fof_disp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_disp.cpp.o
.PHONY : FOF_UNIX_LIB/fof_disp.cpp.o

FOF_UNIX_LIB/fof_disp.i: FOF_UNIX_LIB/fof_disp.cpp.i
.PHONY : FOF_UNIX_LIB/fof_disp.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_disp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_disp.cpp.i
.PHONY : FOF_UNIX_LIB/fof_disp.cpp.i

FOF_UNIX_LIB/fof_disp.s: FOF_UNIX_LIB/fof_disp.cpp.s
.PHONY : FOF_UNIX_LIB/fof_disp.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_disp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_disp.cpp.s
.PHONY : FOF_UNIX_LIB/fof_disp.cpp.s

FOF_UNIX_LIB/fof_duf.o: FOF_UNIX_LIB/fof_duf.cpp.o
.PHONY : FOF_UNIX_LIB/fof_duf.o

# target to build an object file
FOF_UNIX_LIB/fof_duf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_duf.cpp.o
.PHONY : FOF_UNIX_LIB/fof_duf.cpp.o

FOF_UNIX_LIB/fof_duf.i: FOF_UNIX_LIB/fof_duf.cpp.i
.PHONY : FOF_UNIX_LIB/fof_duf.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_duf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_duf.cpp.i
.PHONY : FOF_UNIX_LIB/fof_duf.cpp.i

FOF_UNIX_LIB/fof_duf.s: FOF_UNIX_LIB/fof_duf.cpp.s
.PHONY : FOF_UNIX_LIB/fof_duf.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_duf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_duf.cpp.s
.PHONY : FOF_UNIX_LIB/fof_duf.cpp.s

FOF_UNIX_LIB/fof_hsf.o: FOF_UNIX_LIB/fof_hsf.cpp.o
.PHONY : FOF_UNIX_LIB/fof_hsf.o

# target to build an object file
FOF_UNIX_LIB/fof_hsf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_hsf.cpp.o
.PHONY : FOF_UNIX_LIB/fof_hsf.cpp.o

FOF_UNIX_LIB/fof_hsf.i: FOF_UNIX_LIB/fof_hsf.cpp.i
.PHONY : FOF_UNIX_LIB/fof_hsf.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_hsf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_hsf.cpp.i
.PHONY : FOF_UNIX_LIB/fof_hsf.cpp.i

FOF_UNIX_LIB/fof_hsf.s: FOF_UNIX_LIB/fof_hsf.cpp.s
.PHONY : FOF_UNIX_LIB/fof_hsf.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_hsf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_hsf.cpp.s
.PHONY : FOF_UNIX_LIB/fof_hsf.cpp.s

FOF_UNIX_LIB/fof_lem.o: FOF_UNIX_LIB/fof_lem.cpp.o
.PHONY : FOF_UNIX_LIB/fof_lem.o

# target to build an object file
FOF_UNIX_LIB/fof_lem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_lem.cpp.o
.PHONY : FOF_UNIX_LIB/fof_lem.cpp.o

FOF_UNIX_LIB/fof_lem.i: FOF_UNIX_LIB/fof_lem.cpp.i
.PHONY : FOF_UNIX_LIB/fof_lem.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_lem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_lem.cpp.i
.PHONY : FOF_UNIX_LIB/fof_lem.cpp.i

FOF_UNIX_LIB/fof_lem.s: FOF_UNIX_LIB/fof_lem.cpp.s
.PHONY : FOF_UNIX_LIB/fof_lem.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_lem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_lem.cpp.s
.PHONY : FOF_UNIX_LIB/fof_lem.cpp.s

FOF_UNIX_LIB/fof_mrt.o: FOF_UNIX_LIB/fof_mrt.cpp.o
.PHONY : FOF_UNIX_LIB/fof_mrt.o

# target to build an object file
FOF_UNIX_LIB/fof_mrt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_mrt.cpp.o
.PHONY : FOF_UNIX_LIB/fof_mrt.cpp.o

FOF_UNIX_LIB/fof_mrt.i: FOF_UNIX_LIB/fof_mrt.cpp.i
.PHONY : FOF_UNIX_LIB/fof_mrt.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_mrt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_mrt.cpp.i
.PHONY : FOF_UNIX_LIB/fof_mrt.cpp.i

FOF_UNIX_LIB/fof_mrt.s: FOF_UNIX_LIB/fof_mrt.cpp.s
.PHONY : FOF_UNIX_LIB/fof_mrt.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_mrt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_mrt.cpp.s
.PHONY : FOF_UNIX_LIB/fof_mrt.cpp.s

FOF_UNIX_LIB/fof_nes.o: FOF_UNIX_LIB/fof_nes.cpp.o
.PHONY : FOF_UNIX_LIB/fof_nes.o

# target to build an object file
FOF_UNIX_LIB/fof_nes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_nes.cpp.o
.PHONY : FOF_UNIX_LIB/fof_nes.cpp.o

FOF_UNIX_LIB/fof_nes.i: FOF_UNIX_LIB/fof_nes.cpp.i
.PHONY : FOF_UNIX_LIB/fof_nes.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_nes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_nes.cpp.i
.PHONY : FOF_UNIX_LIB/fof_nes.cpp.i

FOF_UNIX_LIB/fof_nes.s: FOF_UNIX_LIB/fof_nes.cpp.s
.PHONY : FOF_UNIX_LIB/fof_nes.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_nes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_nes.cpp.s
.PHONY : FOF_UNIX_LIB/fof_nes.cpp.s

FOF_UNIX_LIB/fof_sd.o: FOF_UNIX_LIB/fof_sd.cpp.o
.PHONY : FOF_UNIX_LIB/fof_sd.o

# target to build an object file
FOF_UNIX_LIB/fof_sd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sd.cpp.o
.PHONY : FOF_UNIX_LIB/fof_sd.cpp.o

FOF_UNIX_LIB/fof_sd.i: FOF_UNIX_LIB/fof_sd.cpp.i
.PHONY : FOF_UNIX_LIB/fof_sd.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_sd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sd.cpp.i
.PHONY : FOF_UNIX_LIB/fof_sd.cpp.i

FOF_UNIX_LIB/fof_sd.s: FOF_UNIX_LIB/fof_sd.cpp.s
.PHONY : FOF_UNIX_LIB/fof_sd.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_sd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sd.cpp.s
.PHONY : FOF_UNIX_LIB/fof_sd.cpp.s

FOF_UNIX_LIB/fof_se.o: FOF_UNIX_LIB/fof_se.cpp.o
.PHONY : FOF_UNIX_LIB/fof_se.o

# target to build an object file
FOF_UNIX_LIB/fof_se.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_se.cpp.o
.PHONY : FOF_UNIX_LIB/fof_se.cpp.o

FOF_UNIX_LIB/fof_se.i: FOF_UNIX_LIB/fof_se.cpp.i
.PHONY : FOF_UNIX_LIB/fof_se.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_se.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_se.cpp.i
.PHONY : FOF_UNIX_LIB/fof_se.cpp.i

FOF_UNIX_LIB/fof_se.s: FOF_UNIX_LIB/fof_se.cpp.s
.PHONY : FOF_UNIX_LIB/fof_se.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_se.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_se.cpp.s
.PHONY : FOF_UNIX_LIB/fof_se.cpp.s

FOF_UNIX_LIB/fof_sgv.o: FOF_UNIX_LIB/fof_sgv.cpp.o
.PHONY : FOF_UNIX_LIB/fof_sgv.o

# target to build an object file
FOF_UNIX_LIB/fof_sgv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sgv.cpp.o
.PHONY : FOF_UNIX_LIB/fof_sgv.cpp.o

FOF_UNIX_LIB/fof_sgv.i: FOF_UNIX_LIB/fof_sgv.cpp.i
.PHONY : FOF_UNIX_LIB/fof_sgv.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_sgv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sgv.cpp.i
.PHONY : FOF_UNIX_LIB/fof_sgv.cpp.i

FOF_UNIX_LIB/fof_sgv.s: FOF_UNIX_LIB/fof_sgv.cpp.s
.PHONY : FOF_UNIX_LIB/fof_sgv.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_sgv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sgv.cpp.s
.PHONY : FOF_UNIX_LIB/fof_sgv.cpp.s

FOF_UNIX_LIB/fof_sh.o: FOF_UNIX_LIB/fof_sh.cpp.o
.PHONY : FOF_UNIX_LIB/fof_sh.o

# target to build an object file
FOF_UNIX_LIB/fof_sh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sh.cpp.o
.PHONY : FOF_UNIX_LIB/fof_sh.cpp.o

FOF_UNIX_LIB/fof_sh.i: FOF_UNIX_LIB/fof_sh.cpp.i
.PHONY : FOF_UNIX_LIB/fof_sh.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_sh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sh.cpp.i
.PHONY : FOF_UNIX_LIB/fof_sh.cpp.i

FOF_UNIX_LIB/fof_sh.s: FOF_UNIX_LIB/fof_sh.cpp.s
.PHONY : FOF_UNIX_LIB/fof_sh.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_sh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sh.cpp.s
.PHONY : FOF_UNIX_LIB/fof_sh.cpp.s

FOF_UNIX_LIB/fof_sha.o: FOF_UNIX_LIB/fof_sha.cpp.o
.PHONY : FOF_UNIX_LIB/fof_sha.o

# target to build an object file
FOF_UNIX_LIB/fof_sha.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sha.cpp.o
.PHONY : FOF_UNIX_LIB/fof_sha.cpp.o

FOF_UNIX_LIB/fof_sha.i: FOF_UNIX_LIB/fof_sha.cpp.i
.PHONY : FOF_UNIX_LIB/fof_sha.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_sha.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sha.cpp.i
.PHONY : FOF_UNIX_LIB/fof_sha.cpp.i

FOF_UNIX_LIB/fof_sha.s: FOF_UNIX_LIB/fof_sha.cpp.s
.PHONY : FOF_UNIX_LIB/fof_sha.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_sha.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_sha.cpp.s
.PHONY : FOF_UNIX_LIB/fof_sha.cpp.s

FOF_UNIX_LIB/fof_soi.o: FOF_UNIX_LIB/fof_soi.cpp.o
.PHONY : FOF_UNIX_LIB/fof_soi.o

# target to build an object file
FOF_UNIX_LIB/fof_soi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_soi.cpp.o
.PHONY : FOF_UNIX_LIB/fof_soi.cpp.o

FOF_UNIX_LIB/fof_soi.i: FOF_UNIX_LIB/fof_soi.cpp.i
.PHONY : FOF_UNIX_LIB/fof_soi.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_soi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_soi.cpp.i
.PHONY : FOF_UNIX_LIB/fof_soi.cpp.i

FOF_UNIX_LIB/fof_soi.s: FOF_UNIX_LIB/fof_soi.cpp.s
.PHONY : FOF_UNIX_LIB/fof_soi.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_soi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_soi.cpp.s
.PHONY : FOF_UNIX_LIB/fof_soi.cpp.s

FOF_UNIX_LIB/fof_unix.o: FOF_UNIX_LIB/fof_unix.cpp.o
.PHONY : FOF_UNIX_LIB/fof_unix.o

# target to build an object file
FOF_UNIX_LIB/fof_unix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_unix.cpp.o
.PHONY : FOF_UNIX_LIB/fof_unix.cpp.o

FOF_UNIX_LIB/fof_unix.i: FOF_UNIX_LIB/fof_unix.cpp.i
.PHONY : FOF_UNIX_LIB/fof_unix.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_unix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_unix.cpp.i
.PHONY : FOF_UNIX_LIB/fof_unix.cpp.i

FOF_UNIX_LIB/fof_unix.s: FOF_UNIX_LIB/fof_unix.cpp.s
.PHONY : FOF_UNIX_LIB/fof_unix.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_unix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_unix.cpp.s
.PHONY : FOF_UNIX_LIB/fof_unix.cpp.s

FOF_UNIX_LIB/fof_util.o: FOF_UNIX_LIB/fof_util.cpp.o
.PHONY : FOF_UNIX_LIB/fof_util.o

# target to build an object file
FOF_UNIX_LIB/fof_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_util.cpp.o
.PHONY : FOF_UNIX_LIB/fof_util.cpp.o

FOF_UNIX_LIB/fof_util.i: FOF_UNIX_LIB/fof_util.cpp.i
.PHONY : FOF_UNIX_LIB/fof_util.i

# target to preprocess a source file
FOF_UNIX_LIB/fof_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_util.cpp.i
.PHONY : FOF_UNIX_LIB/fof_util.cpp.i

FOF_UNIX_LIB/fof_util.s: FOF_UNIX_LIB/fof_util.cpp.s
.PHONY : FOF_UNIX_LIB/fof_util.s

# target to generate assembly for a file
FOF_UNIX_LIB/fof_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fofem_c.dir/build.make CMakeFiles/fofem_c.dir/FOF_UNIX_LIB/fof_util.cpp.s
.PHONY : FOF_UNIX_LIB/fof_util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fofem"
	@echo "... fofem_c"
	@echo "... FOF_UNIX/ansi_mai.o"
	@echo "... FOF_UNIX/ansi_mai.i"
	@echo "... FOF_UNIX/ansi_mai.s"
	@echo "... FOF_UNIX/bur_bov.o"
	@echo "... FOF_UNIX/bur_bov.i"
	@echo "... FOF_UNIX/bur_bov.s"
	@echo "... FOF_UNIX/bur_brn.o"
	@echo "... FOF_UNIX/bur_brn.i"
	@echo "... FOF_UNIX/bur_brn.s"
	@echo "... FOF_UNIX/cdf_util.o"
	@echo "... FOF_UNIX/cdf_util.i"
	@echo "... FOF_UNIX/cdf_util.s"
	@echo "... FOF_UNIX/fof_bcm.o"
	@echo "... FOF_UNIX/fof_bcm.i"
	@echo "... FOF_UNIX/fof_bcm.s"
	@echo "... FOF_UNIX/fof_ci.o"
	@echo "... FOF_UNIX/fof_ci.i"
	@echo "... FOF_UNIX/fof_ci.s"
	@echo "... FOF_UNIX/fof_cm.o"
	@echo "... FOF_UNIX/fof_cm.i"
	@echo "... FOF_UNIX/fof_cm.s"
	@echo "... FOF_UNIX/fof_co.o"
	@echo "... FOF_UNIX/fof_co.i"
	@echo "... FOF_UNIX/fof_co.s"
	@echo "... FOF_UNIX/fof_disp.o"
	@echo "... FOF_UNIX/fof_disp.i"
	@echo "... FOF_UNIX/fof_disp.s"
	@echo "... FOF_UNIX/fof_duf.o"
	@echo "... FOF_UNIX/fof_duf.i"
	@echo "... FOF_UNIX/fof_duf.s"
	@echo "... FOF_UNIX/fof_hsf.o"
	@echo "... FOF_UNIX/fof_hsf.i"
	@echo "... FOF_UNIX/fof_hsf.s"
	@echo "... FOF_UNIX/fof_lem.o"
	@echo "... FOF_UNIX/fof_lem.i"
	@echo "... FOF_UNIX/fof_lem.s"
	@echo "... FOF_UNIX/fof_mrt.o"
	@echo "... FOF_UNIX/fof_mrt.i"
	@echo "... FOF_UNIX/fof_mrt.s"
	@echo "... FOF_UNIX/fof_nes.o"
	@echo "... FOF_UNIX/fof_nes.i"
	@echo "... FOF_UNIX/fof_nes.s"
	@echo "... FOF_UNIX/fof_sd.o"
	@echo "... FOF_UNIX/fof_sd.i"
	@echo "... FOF_UNIX/fof_sd.s"
	@echo "... FOF_UNIX/fof_se.o"
	@echo "... FOF_UNIX/fof_se.i"
	@echo "... FOF_UNIX/fof_se.s"
	@echo "... FOF_UNIX/fof_sgv.o"
	@echo "... FOF_UNIX/fof_sgv.i"
	@echo "... FOF_UNIX/fof_sgv.s"
	@echo "... FOF_UNIX/fof_sh.o"
	@echo "... FOF_UNIX/fof_sh.i"
	@echo "... FOF_UNIX/fof_sh.s"
	@echo "... FOF_UNIX/fof_sha.o"
	@echo "... FOF_UNIX/fof_sha.i"
	@echo "... FOF_UNIX/fof_sha.s"
	@echo "... FOF_UNIX/fof_soi.o"
	@echo "... FOF_UNIX/fof_soi.i"
	@echo "... FOF_UNIX/fof_soi.s"
	@echo "... FOF_UNIX/fof_unix.o"
	@echo "... FOF_UNIX/fof_unix.i"
	@echo "... FOF_UNIX/fof_unix.s"
	@echo "... FOF_UNIX/fof_util.o"
	@echo "... FOF_UNIX/fof_util.i"
	@echo "... FOF_UNIX/fof_util.s"
	@echo "... FOF_UNIX_LIB/ansi_mai.o"
	@echo "... FOF_UNIX_LIB/ansi_mai.i"
	@echo "... FOF_UNIX_LIB/ansi_mai.s"
	@echo "... FOF_UNIX_LIB/bur_bov.o"
	@echo "... FOF_UNIX_LIB/bur_bov.i"
	@echo "... FOF_UNIX_LIB/bur_bov.s"
	@echo "... FOF_UNIX_LIB/bur_brn.o"
	@echo "... FOF_UNIX_LIB/bur_brn.i"
	@echo "... FOF_UNIX_LIB/bur_brn.s"
	@echo "... FOF_UNIX_LIB/cdf_util.o"
	@echo "... FOF_UNIX_LIB/cdf_util.i"
	@echo "... FOF_UNIX_LIB/cdf_util.s"
	@echo "... FOF_UNIX_LIB/fof_bcm.o"
	@echo "... FOF_UNIX_LIB/fof_bcm.i"
	@echo "... FOF_UNIX_LIB/fof_bcm.s"
	@echo "... FOF_UNIX_LIB/fof_ci.o"
	@echo "... FOF_UNIX_LIB/fof_ci.i"
	@echo "... FOF_UNIX_LIB/fof_ci.s"
	@echo "... FOF_UNIX_LIB/fof_cm.o"
	@echo "... FOF_UNIX_LIB/fof_cm.i"
	@echo "... FOF_UNIX_LIB/fof_cm.s"
	@echo "... FOF_UNIX_LIB/fof_co.o"
	@echo "... FOF_UNIX_LIB/fof_co.i"
	@echo "... FOF_UNIX_LIB/fof_co.s"
	@echo "... FOF_UNIX_LIB/fof_disp.o"
	@echo "... FOF_UNIX_LIB/fof_disp.i"
	@echo "... FOF_UNIX_LIB/fof_disp.s"
	@echo "... FOF_UNIX_LIB/fof_duf.o"
	@echo "... FOF_UNIX_LIB/fof_duf.i"
	@echo "... FOF_UNIX_LIB/fof_duf.s"
	@echo "... FOF_UNIX_LIB/fof_hsf.o"
	@echo "... FOF_UNIX_LIB/fof_hsf.i"
	@echo "... FOF_UNIX_LIB/fof_hsf.s"
	@echo "... FOF_UNIX_LIB/fof_lem.o"
	@echo "... FOF_UNIX_LIB/fof_lem.i"
	@echo "... FOF_UNIX_LIB/fof_lem.s"
	@echo "... FOF_UNIX_LIB/fof_mrt.o"
	@echo "... FOF_UNIX_LIB/fof_mrt.i"
	@echo "... FOF_UNIX_LIB/fof_mrt.s"
	@echo "... FOF_UNIX_LIB/fof_nes.o"
	@echo "... FOF_UNIX_LIB/fof_nes.i"
	@echo "... FOF_UNIX_LIB/fof_nes.s"
	@echo "... FOF_UNIX_LIB/fof_sd.o"
	@echo "... FOF_UNIX_LIB/fof_sd.i"
	@echo "... FOF_UNIX_LIB/fof_sd.s"
	@echo "... FOF_UNIX_LIB/fof_se.o"
	@echo "... FOF_UNIX_LIB/fof_se.i"
	@echo "... FOF_UNIX_LIB/fof_se.s"
	@echo "... FOF_UNIX_LIB/fof_sgv.o"
	@echo "... FOF_UNIX_LIB/fof_sgv.i"
	@echo "... FOF_UNIX_LIB/fof_sgv.s"
	@echo "... FOF_UNIX_LIB/fof_sh.o"
	@echo "... FOF_UNIX_LIB/fof_sh.i"
	@echo "... FOF_UNIX_LIB/fof_sh.s"
	@echo "... FOF_UNIX_LIB/fof_sha.o"
	@echo "... FOF_UNIX_LIB/fof_sha.i"
	@echo "... FOF_UNIX_LIB/fof_sha.s"
	@echo "... FOF_UNIX_LIB/fof_soi.o"
	@echo "... FOF_UNIX_LIB/fof_soi.i"
	@echo "... FOF_UNIX_LIB/fof_soi.s"
	@echo "... FOF_UNIX_LIB/fof_unix.o"
	@echo "... FOF_UNIX_LIB/fof_unix.i"
	@echo "... FOF_UNIX_LIB/fof_unix.s"
	@echo "... FOF_UNIX_LIB/fof_util.o"
	@echo "... FOF_UNIX_LIB/fof_util.i"
	@echo "... FOF_UNIX_LIB/fof_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

